name: J4 Download Installer Translations Crowdin Action
# Controls when the action will run. 
on:
  # Runs once a day at 1:01
  schedule:
    - cron:  '01 1 * * *'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel  
jobs:
  synchronize-with-crowdin:
    if: (github.event_name == 'schedule' && github.repository == 'joomla/core-translations') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

#   Joomla INI not ready yet
#    - name: Crowdin Download Albanian
#      uses: crowdin/github-action@1.3.2
#      with:
#        config: 'Configurations/Crowdin-J4-Installer.yml'
#        upload_sources: false
#        download_translations: true
#        download_language: sq
#        skip_untranslated_strings: true
#        export_only_approved: true
#        commit_message: 'New Albanian Crowdin translations by Github Action'

#      "LanguageName": "Afrikaans",
#      "CrowdinID": "af"

#      "LanguageName": "Amharic",
#      "CrowdinID": "am"

    - name: Crowdin Download Arabic
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: ar
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Arabic Crowdin translations by Github Action'

#      "LanguageName": "Armenian",
#      "CrowdinID": "hy"

#      "LanguageName": "Azerbaijani",
#      "CrowdinID": "az"

    - name: Crowdin Download Basque
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: eu
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Basque Crowdin translations by Github Action'

#      "LanguageName": "Bengali",
#      "CrowdinID": "bn"

#      "LanguageName": "Bosnian",
#      "CrowdinID": "bs"

#      "LanguageName": "Bulgarian",
#      "CrowdinID": "bg-BG"

#      "LanguageName": "Catalan",
#      "CrowdinID": "ca"

#      "LanguageName": "Chinese Simplified",
#      "CrowdinID": "zh-CN"

    - name: Crowdin Download Chinese Traditional
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: zh-TW
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Chinese Traditional Crowdin translations by Github Action'

#      "LanguageName": "Croatian",
#      "CrowdinID": "hr"

    - name: Crowdin Download Czech
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: cs
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Czech Crowdin translations by Github Action'

    - name: Crowdin Download Danish
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: da
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Danish Crowdin translations by Github Action'

#      "LanguageName": "Dari",
#      "CrowdinID": "fa-AF"

    - name: Crowdin Download Dutch
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: nl
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Dutch Crowdin translations by Github Action'

    - name: Crowdin Download Dutch Belgium
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: nl-BE
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Dutch Belgium Crowdin translations by Github Action'

    - name: Crowdin Download English Australia
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: en-AU
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New English Australia Crowdin translations by Github Action'

#      "LanguageName": "English, Canada",
#      "CrowdinID": "en-CA"

    - name: Crowdin Download English US
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: en-US
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New English US Crowdin translations by Github Action'

#      "LanguageName": "Esperanto",
#      "CrowdinID": "eo"
      
    - name: Crowdin Download Estonian
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: et
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Estonian Crowdin translations by Github Action'

#      "LanguageName": "Finnish",
#      "CrowdinID": "fi"

    - name: Crowdin Download French
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: fr
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New French Crowdin translations by Github Action'

#      "LanguageName": "French, Canada",
#      "CrowdinID": "fr-CA"

#      "LanguageName": "Galician",
#      "CrowdinID": "gl"

    - name: Crowdin Download Georgian
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: ka
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Georgian Crowdin translations by Github Action'

    - name: Crowdin Download Greek
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: el
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Greek Crowdin translations by Github Action'

#      "LanguageName": "Gujarati",
#      "CrowdinID": "gu"

# German doesn't use Crowdin
# German Austria doesn't use Crowdin
# German Liechtenstein doesn't use Crowdin
# German Luxombourg doesn't use Crowdin
# German Swiss doesn't use Crowdin

#      "LanguageName": "Hebrew",
#      "CrowdinID": "he"

#      "LanguageName": "Hindi",
#      "CrowdinID": "hi"

    - name: Crowdin Download Hungarian
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: hu
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Hungarian Crowdin translations by Github Action'

#      "LanguageName": "Indonesian",
#      "CrowdinID": "id"

#      "LanguageName": "Irish",
#      "CrowdinID": "ga"

    - name: Crowdin Download Italian
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: it
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Italian Crowdin translations by Github Action'

    - name: Crowdin Download Japanese
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: ja
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Japanese Crowdin translations by Github Action'

#      "LanguageName": "Kazakh",
#      "CrowdinID": "kk"

#      "LanguageName": "Khmer",
#      "CrowdinID": "km"

#      "LanguageName": "Korean",
#      "CrowdinID": "ko"

#      "LanguageName": "Kyrgyz",
#      "CrowdinID": "ky"

#      "LanguageName": "Lao",
#      "CrowdinID": "lo"

#      "LanguageName": "Latvian",
#      "CrowdinID": "lv"

#      "LanguageName": "Lithuanian",
#      "CrowdinID": "lt"

#      "LanguageName": "Macedonian",
#      "CrowdinID": "mk"

#      "LanguageName": "Malay",
#      "CrowdinID": "ms"

#      "LanguageName": "Malayalam",
#      "CrowdinID": "ml"

#      "LanguageName": "Mongolian",
#      "CrowdinID": "mn"

#      "LanguageName": "Northern Sami",
#      "CrowdinID": "se"

# Joomla INI not ready yet
#    - name: Crowdin Download Norwegian Bokmal
#      uses: crowdin/github-action@1.3.2
#      with:
#        config: 'Configurations/Crowdin-J4-Installer.yml'
#        upload_sources: false
#        download_translations: true
#        download_language: nb
#        skip_untranslated_strings: true
#        export_only_approved: true
#        commit_message: 'New Norwegian Bokmal Crowdin translations by Github Action'

#      "LanguageName": "Norwegian Nynorsk",
#      "CrowdinID": "nn-NO"

#      "LanguageName": "Occitan",
#      "CrowdinID": "oc"

    - name: Crowdin Download Persian
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: fa
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Persian Crowdin translations by Github Action'

    - name: Crowdin Download Polish
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: pl
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Polish Crowdin translations by Github Action'

    - name: Crowdin Download Portuguese
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: pt
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Portuguese Crowdin translations by Github Action'

#      "LanguageName": "Portuguese, Brazilian",
#      "CrowdinID": "pt-BR"

    - name: Crowdin Download Romanian
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: ro
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Romanian Crowdin translations by Github Action'

    - name: Crowdin Download Russian
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: ru
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Russian Crowdin translations by Github Action'

#      "LanguageName": "Serbian (Cyrillic)",
#      "CrowdinID": "sr-Cyrl"

#      "LanguageName": "Serbian (Latin)",
#      "CrowdinID": "sr-Latn"

#      "LanguageName": "Sinhala",
#      "CrowdinID": "si"

    - name: Crowdin Download Slovak
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: sk
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Slovak Crowdin translations by Github Action'

    - name: Crowdin Download Slovenian
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: sl
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Slovenian Crowdin translations by Github Action'

    - name: Crowdin Download Spanish
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: es
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Spanish Crowdin translations by Github Action'

#      "LanguageName": "Spanish, Colombia",
#      "CrowdinID": "es-CO"

#      "LanguageName": "Spanish, Mexico",
#      "CrowdinID": "es-MX"

#      "LanguageName": "Swahili",
#      "CrowdinID": "sw"

    - name: Crowdin Download Swedish
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: sv
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Swedish Crowdin translations by Github Action'

#      "LanguageName": "Syriac",
#      "CrowdinID": "syc"

#      "LanguageName": "Tagalog",
#      "CrowdinID": "tl"

    - name: Crowdin Download Tamil
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: ta
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Tamil Crowdin translations by Github Action'

    - name: Crowdin Download Thai
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: th
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Thai Crowdin translations by Github Action'

    - name: Crowdin Download Turkish
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: tr
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Turkish Crowdin translations by Github Action'

#      "LanguageName": "Turkmen",
#      "CrowdinID": "tk"

#      "LanguageName": "Ukrainian",
#      "CrowdinID": "uk"

#      "LanguageName": "Urdu (India)",
#      "CrowdinID": "ur-IN"

#      "LanguageName": "Urdu (Pakistan)",
#      "CrowdinID": "ur"

#      "LanguageName": "Uyghur",
#      "CrowdinID": "ug"

#      "LanguageName": "Vietnamese",
#      "CrowdinID": "vi"

    - name: Crowdin Download Welsh
      uses: crowdin/github-action@1.3.2
      with:
        config: 'Configurations/Crowdin-J4-Installer.yml'
        upload_sources: false
        download_translations: true
        download_language: cy
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Welsh Crowdin translations by Github Action'
