name: J4 Download Installer Translations Crowdin Action
# Controls when the action will run. 
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel  
jobs:
  synchronize-with-crowdin:
    if: (github.event_name == 'schedule' && github.repository == 'joomla/core-translations') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    - name: Crowdin Download Arabic
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: ar
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Arabic Crowdin translations by Github Action'

    - name: Crowdin Download Basque
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: eu
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Basque Crowdin translations by Github Action'

    - name: Crowdin Download Czech
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: cs
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Czech Crowdin translations by Github Action'

    - name: Crowdin Download Danish
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: da
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Danish Crowdin translations by Github Action'

    - name: Crowdin Download Dutch
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: nl
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Dutch Crowdin translations by Github Action'

    - name: Crowdin Download Dutch Belgium
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: nl-BE
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Dutch Belgium Crowdin translations by Github Action'

    - name: Crowdin Download English Australia
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: en-AU
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New English Australia Crowdin translations by Github Action'

    - name: Crowdin Download English US
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: en-US
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New English US Crowdin translations by Github Action'

    - name: Crowdin Download Estonian
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: et
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Estonian Crowdin translations by Github Action'

    - name: Crowdin Download French
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: fr
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New French Crowdin translations by Github Action'

# German doesn't use Crowdin
# German Austria doesn't use Crowdin
# German Liechtenstein doesn't use Crowdin
# German Luxombourg doesn't use Crowdin

    - name: Crowdin Download Hungarian
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: hu
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Hungarian Crowdin translations by Github Action'

    - name: Crowdin Download Italian
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: it
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Italian Crowdin translations by Github Action'

    - name: Crowdin Download Persian
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: fa
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Persian Crowdin translations by Github Action'

    - name: Crowdin Download Polish
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: pl
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Polish Crowdin translations by Github Action'

    - name: Crowdin Download Portuguese
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: pt
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Portuguese Crowdin translations by Github Action'

# Russian doesn't use Crowdin

    - name: Crowdin Download Slovak
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: sk
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Slovak Crowdin translations by Github Action'

    - name: Crowdin Download Slovenian
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: sl
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Slovenian Crowdin translations by Github Action'

# Spanish doesn't use Crowdin

    - name: Crowdin Download Swedish
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: sv
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Swedish Crowdin translations by Github Action'

    - name: Crowdin Download Tamil
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: ta
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Tamil Crowdin translations by Github Action'

    - name: Crowdin Download Welsh
      uses: crowdin/github-action@1.3.0
      with:
        config: 'Configurations/Crowdin-J4-All.yml'
        upload_sources: false
        download_translations: true
        download_language: cy
        skip_untranslated_strings: true
        export_only_approved: true
        commit_message: 'New Welsh Crowdin translations by Github Action'

