# This workflow fetches the Japanese V4 Version of the Joomla CMS and syncs the needed translation language files
# into the core-translations repository. After this it creates a new commit.
# The second part uploads the translation to the CMS Crowdin project.

name: J4 Get Japanese Translation files

on:
  workflow_dispatch:
  # Runs once a day at 8:01
  schedule:
    - cron:  '31 8 * * *'

jobs:
  collect-from-external:
    if: (github.event_name == 'schedule' && github.repository == 'joomla/core-translations') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch and extract Japanese j4 cms
        run: |
          cd ..
          ls -l
          wget -nv "https://github.com/joomlajp/Joomla-in-Japanese/archive/refs/heads/4.x.zip"
          unzip 4.x.zip

      - name: Syncing j4 directories
        # We use a simple copy paste syntax here if needed customization for different directories
        run: |
          cd ..
          SYNC_VERION="v4"
          LANGUAGE_CODE="ja-JP"

          ZIP_PATH="administrator/language/${LANGUAGE_CODE}/"
          REPO_PATH="${LANGUAGE_CODE}/administrator/language/${LANGUAGE_CODE}/"
          echo /${ZIP_PATH}
          echo /${REPO_PATH}
          rsync -i -rptgo --checksum --ignore-times --delete  Joomla-in-Japanese-4.x/${ZIP_PATH} core-translations/joomla_${SYNC_VERION}/translations/package/${REPO_PATH}

          ZIP_PATH="pkg_ja-JP.xml"
          REPO_PATH="${LANGUAGE_CODE}/"
          echo /${ZIP_PATH}
          echo /${REPO_PATH}
          rsync -i -rptgo --checksum --ignore-times --delete  Joomla-in-Japanese-4.x/${ZIP_PATH} core-translations/joomla_${SYNC_VERION}/translations/package/${REPO_PATH}

          ZIP_PATH="api/language/${LANGUAGE_CODE}/"
          REPO_PATH="${LANGUAGE_CODE}/api/language/${LANGUAGE_CODE}/"
          echo /${ZIP_PATH}
          echo /${REPO_PATH}
          rsync -i -rptgo --checksum --ignore-times --delete  Joomla-in-Japanese-4.x/${ZIP_PATH} core-translations/joomla_${SYNC_VERION}/translations/package/${REPO_PATH}

          ZIP_PATH="language/${LANGUAGE_CODE}/"
          REPO_PATH="${LANGUAGE_CODE}/language/${LANGUAGE_CODE}/"
          echo /${ZIP_PATH}
          echo /${REPO_PATH}
          rsync -i -rptgo --checksum --ignore-times --delete  Joomla-in-Japanese-4.x/${ZIP_PATH} core-translations/joomla_${SYNC_VERION}/translations/package/${REPO_PATH}

      - name: Validate PHP code
        run: |
          SYNC_VERION="v4"
          LANGUAGE_CODE="ja-JP"
          find ./joomla_${SYNC_VERION}/translations/package/${LANGUAGE_CODE}/ -name "*.php" -exec php -l {} \; | fgrep -i "PHP Parse Error" || exit 1
