# This workflow fetches the Ukrainian V4 Version of the Joomla CMS and syncs the needed translation language files
# into the core-translations repository. After this it creates a new commit.
# The second part uploads the translation to the CMS Crowdin project.

name: J4 Get Ukrainian Translation files

on:
  workflow_dispatch:
  # Runs once a day at 8:01
  schedule:
    - cron:  '31 8 * * *'

jobs:
  collect-from-external:
    if: (github.event_name == 'schedule' && github.repository == 'joomla/core-translations') || (github.event_name != 'schedule')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch and extract Ukrainian j4 cms
        run: |
          cd ..
          ls -l
          wget -nv "https://github.com/Joomla-Ukraine/uk-UA/archive/refs/heads/4.x.zip"
          unzip 4.x.zip

      - name: Syncing j4 directories
        # We use a simple copy paste syntax here if needed customization for different directories
        run: |
          cd ..
          SYNC_VERION="v4"
          LANGUAGE_CODE="uk-UA"

          ZIP_PATH="administrator/language/${LANGUAGE_CODE}/"
          REPO_PATH="${LANGUAGE_CODE}/administrator/language/${LANGUAGE_CODE}/"
          echo /${ZIP_PATH}
          echo /${REPO_PATH}
          rsync -i -rptgo --checksum --ignore-times --delete  uk-UA-4.x/${ZIP_PATH} core-translations/joomla_${SYNC_VERION}/translations/package/${REPO_PATH}

          ZIP_PATH="pkg_uk-UA.xml"
          REPO_PATH="${LANGUAGE_CODE}/"
          echo /${ZIP_PATH}
          echo /${REPO_PATH}
          rsync -i -rptgo --checksum --ignore-times --delete  uk-UA-4.x/${ZIP_PATH} core-translations/joomla_${SYNC_VERION}/translations/package/${REPO_PATH}

          ZIP_PATH="api/language/${LANGUAGE_CODE}/"
          REPO_PATH="${LANGUAGE_CODE}/api/language/${LANGUAGE_CODE}/"
          echo /${ZIP_PATH}
          echo /${REPO_PATH}
          rsync -i -rptgo --checksum --ignore-times --delete  uk-UA-4.x/${ZIP_PATH} core-translations/joomla_${SYNC_VERION}/translations/package/${REPO_PATH}

          ZIP_PATH="language/${LANGUAGE_CODE}/"
          REPO_PATH="${LANGUAGE_CODE}/language/${LANGUAGE_CODE}/"
          echo /${ZIP_PATH}
          echo /${REPO_PATH}
          rsync -i -rptgo --checksum --ignore-times --delete  uk-UA-4.x/${ZIP_PATH} core-translations/joomla_${SYNC_VERION}/translations/package/${REPO_PATH}

      - name: Validate PHP code
        run: |
          find . -name "*.php" -exec php -l {} \;
